{% set name = "cohesion" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mschwager/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: af076ebb63993ba043ea54ae20426ca7a2cc862effd28fd47f7c5b73a6e6fb99

build:
  noarch: python
  number: 0
  entry_points:
    - cohesion = cohesion.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - cohesion -h
    - flake8 --version | grep cohesion
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/mschwager/cohesion
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tool for measuring Python class cohesion. Optional flake8 extension.

extra:
  recipe-maintainers:
    - thewchan
